/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.aurelien.swingDB.frame;

import fr.aurelien.database.utils.DatabaseConnection;
import fr.aurelien.swingDB.DAO.DAOInterface;
import fr.aurelien.swingDB.DAO.StudentDAO;
import fr.aurelien.swingDB.entity.Student;
import static java.awt.Color.RED;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.border.Border;

/**
 *
 * @author formation
 */
public class StudentInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form StudentInternalFrame
     */
    public StudentInternalFrame() {
        initComponents();
        initStudentList();

    }

    //on cree une methode d'initialisation pour la liste
    private void initStudentList() {
        // Récupération du Model

        try {
            Connection cn = DatabaseConnection.getInstance();

            DefaultListModel listModel = new DefaultListModel();
            listModel.clear();

            StudentDAO dao = new StudentDAO(cn);
            List<Student> data = dao.findAll().getAll();

            for (Student student : data) {
                listModel.addElement(student);

            }

            studentList.setModel(listModel);

        } catch (SQLException ex) {
            Logger.getLogger(StudentInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Remise à zero de la liste
        //Instanciation du DAO
        // Récupération de la liste des étudiants
        // Remplissage du model à partir de la requette
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        FemmeRadioButton = new javax.swing.JRadioButton();
        hommeRadioButton = new javax.swing.JRadioButton();
        addStudentButton = new javax.swing.JButton();
        ageTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentList = new javax.swing.JList<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Goudy Stout", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Etudiants");

        firstNameLabel.setText("Prenom");

        nameLabel.setText("Nom");

        buttonGroup1.add(FemmeRadioButton);
        FemmeRadioButton.setText("Femminin");
        FemmeRadioButton.setActionCommand("F");

        buttonGroup1.add(hommeRadioButton);
        hommeRadioButton.setSelected(true);
        hommeRadioButton.setText("Masculin");
        hommeRadioButton.setActionCommand("M");

        addStudentButton.setText("Ajouter Etudiant");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        ageTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageTextField1FocusLost(evt);
            }
        });
        ageTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("age:");

        studentList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(studentList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudentButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FemmeRadioButton)
                        .addGap(10, 10, 10)
                        .addComponent(hommeRadioButton))
                    .addComponent(ageTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(nameLabel)
                    .addComponent(jLabel2))
                .addGap(147, 147, 147)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ageTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FemmeRadioButton)
                            .addComponent(hommeRadioButton))
                        .addGap(18, 18, 18)
                        .addComponent(addStudentButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        // Définition des variables
        String prenom = firstNameField.getText();
        String nom = nameField.getText();
        // Définition des Action Command car bug dans NetBean en mode graphique
        hommeRadioButton.setActionCommand("M");
        FemmeRadioButton.setActionCommand("F");
        // affectation de la variable 
        char sexe = buttonGroup1.getSelection().getActionCommand().charAt(0);
        try {
            Connection cn = DatabaseConnection.getInstance();
            Student addStudent = new Student(nom, prenom, sexe);

            StudentDAO dao = new StudentDAO(cn);
            dao.save(addStudent);

        } catch (SQLException ex) {
            Logger.getLogger(StudentInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        initStudentList();
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void ageTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextField1ActionPerformed

    private void ageTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageTextField1FocusLost
        String age = (ageTextField1).toString();
        try {
            Integer intAge = Integer.parseInt(age);

        } catch (NumberFormatException e) {

            ageTextField1.setBorder((Border) RED);
            addStudentButton.setEnabled(false);

            Logger.getLogger(StudentInternalFrame.class.getName()).log(Level.SEVERE, null, e);
        }


    }//GEN-LAST:event_ageTextField1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton FemmeRadioButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JTextField ageTextField1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JRadioButton hommeRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JList<String> studentList;
    // End of variables declaration//GEN-END:variables
}
